[package]
name = "zune-jpeg"
version = "0.1.0"
authors = ["caleb <etemesicaleb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"

[dev-dependencies]
criterion="0.3"

[[bench]]
name="yuv_to_rgb"
harness=false

[[bench]]
name="decode"
harness=false


[profile.bench]
debug = true
