[package]
name = "zune-jpeg"
version = "0.1.0"
authors = ["caleb <etemesicaleb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zune-traits = {path = "../zune-traits",features =["async-trait"]}
ndarray = "0.14.0"
log = "0.4.11"
byteorder="1.3.4"
threadpool = "1.8.1"

[dev-dependencies]
criterion="0.3"

[[bench]]
name="yuv_to_rgb"
harness=false